export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  smtpHost: process.env.SMTP_HOST ?? "",
  smtpPort: Number(process.env.SMTP_PORT ?? "587"),
  smtpSecure: process.env.SMTP_SECURE === "true",
  smtpUser: process.env.SMTP_USER ?? "",
  smtpPassword: process.env.SMTP_PASSWORD ?? "",
  emailFrom: process.env.EMAIL_FROM ?? "",
  appBaseUrl: process.env.APP_BASE_URL ?? "http://localhost:3000",
  customerSessionSecret: process.env.CUSTOMER_SESSION_SECRET ?? process.env.JWT_SECRET ?? "",
  payflowApiKey: process.env.PAYFLOW_API_KEY ?? "",
  payflowApiSecret: process.env.PAYFLOW_API_SECRET ?? "",
  payflowBaseUrl: process.env.PAYFLOW_BASE_URL ?? "https://payflow.top/api/v2",
};
